services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${GO_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${GO_DATABASE_USER}
      POSTGRES_PASSWORD: ${GO_DATABASE_PASSWORD}
      POSTGRES_DB: ${GO_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
